### PR TITLE
Cross-platform WinForms implementation though mono

### PR DESCRIPTION
**Pull request by jeremyVignelles**
Tested on linux, untested on mono windows and mono mac.

### CODE REVIEW

**Comment by mfkl** [comment]
I'm a bit conflicted regarding this PR.

On the one hand, the changes are fairly small, so, free lunch?

On the other hand...
- Mono's implementation of WinForms hasn't been actively maintained since 10 years. What's the point of us supporting it? Our limited time would probably better spent else where, don't you think? It's not because it can be done that it should be done :)
- The number of interested users is probably gonna be _very_ low.
- More support issues to answer to, more code to maintain.

WinForms got opensourced recently, but it was made clear by MSFT that it'd not be ported crossplatform.

Anyway, I will have a quick look at if your PR works on all platforms, whatever we decide.

And since there is no rush, I'd be of the opinion of first merging WinForms support for .NET Framework on Windows first, and see about the rest in a separate PR later.

**Comment by jeremyVignelles** [comment]
I agree that WinForms seems to be a dying platform, especially on mono.

However :

- It seems that commits are still being made to this : https://github.com/mono/mono/commits/master/mcs/class/System.Windows.Forms
- The same entry points (`.XWindow` and `.NsObject`) are already used in the GTK implementation. Thus, the risk is very low to have a bug very specific to the WinForms that we wouldn't have seen in GTK.
- Having the support of several alternatives for a given OS would be a plus I think.

**Comment by mfkl** [comment]
So, I tried running this on mac and it failed. Few reasons from my initial analysis:
- https://github.com/videolan/libvlcsharp/blob/2cd473acc8ddb35c9437c86826108053788077a1/LibVLCSharp/Shared/PlatformHelper.cs#L29 This needs changing. No way to differentiate between Linux and Mac on .NET40. That means we would need to support both net40 and net47 for the WinForms package. And hope WinForms net40 still works on Windows.
- the libvlc mac nuget package seems to get installed properly, but the dylib is not copied to the output folder. This should be working, it does for netcoreapp and net40 gtk. https://github.com/mfkl/libvlc-nuget/commit/cc979700f0312264469a8ea17de756639ea1d107 but that requires more troubleshooting coz I don't know why it's failing.
- No debugging in VS. I haven't tried setting up monodevelop or VS Code.

It's not a plug and play change, it requires changes probably in libvlc mac packaging and almost definitely to the Core libvlcsharp package. Given that:
- Not one mainstream library supports WinForms on Mono mac/linux (look at mvvmcross, reactiveui, skiasharp, etc.)
- There is no significant user demand.
- It does require work and our time is limited and IMHO better spent elsewhere.
- Even if it has some git activity, WinForms on mono is not really developed https://twitter.com/migueldeicaza/status/1088260481108885504

With .NET Core 3.0 support for WinForms and WPF, I think it is possible that the community ports WinForms to Linux/Mac somehow. We can see then, if it's worth having a look at this again.

**Comment by jeremyVignelles** [comment]
Totally agree. Mac seems like a hard platform to work with...
Let's give this up.

**Comment by mfkl** [comment]
Ok, closing this then.

**Pull request closed without merging**
